version: "2.1"

services:
  postgres:
    image: postgres:13.0
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - config-dev.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - fpl-find-a-manager-data:/var/lib/postgresql/data
  app:
    image: fpl-find-a-manager
    ports:
      - 3000:3000
    env_file:
      - config-dev.env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
    fpl-find-a-manager-data: